### ISSUE TITLE
Breaking change with 0.12.3 & secio

### ISSUE THREAD

**Issue by jacogr** [libp2p/js-peer-id#100]
This took me a bit to track down. So effectively, the last working version for me in https://github.com/polkadot-js/client in 0.12.2, as soon as I try to upgrade to 0.12.3, I have issues.

So effectively what happens -

- I try to dial a bootnode, e.g. `/ip4/104.211.54.233/tcp/30363/p2p/QmUghPWmHR8pQbZyBMeYzvPcH7VRcTiBibcyBG7wMKHaSZ`
- all ok, flow is as normal and then we get to this part in secio - https://github.com/libp2p/js-libp2p-secio/blob/master/src/handshake/crypto.js#L78

It gets the publicKey from the remote node and then calls to create the id string. Previously this was created via hash, now it gets created via identity. This means that the equality check here fails and we get back `dialed to the wrong peer, Ids do not match`

For now fixed peer-id to 0.12.2 and all is well again.

**Comment by vasco-santos** [comment]
Hey @jacogr 

Thanks for reaching out and sorry for the really late answer. Can you try the latest `0.12.*` and let me know if this problem persists? The `0.12.3` added support for `secp256k1` keys, but the default behavior should be the same. The change for `0.12.3` is the following: https://github.com/libp2p/js-peer-id/commit/17440a3f9a67092499f5cb5c828936a8d06ad990
