### ISSUE TITLE
no documentation for isPeerId

### ISSUE THREAD

**Issue by a1300** [libp2p/js-peer-id#134]
@vasco-santos 

Under which subcategory should `PeerId.isPeerId()` be documented?
Currenty in the `README.md` we have the subcategories
- API
  - Create
  - Import
  - Export

**Comment by vasco-santos** [comment]
humm, not really any of them. Meanwhile, we can add it to a "Others" category.
We will be looking into adding jsdoc everywhere and generate docs from there, not really sure on the structure yet, so we can do this for now
