### ISSUE TITLE
Calling toString on a peer id breaks deep comparison

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-peer-id#141]
```js
const PeerId = require('peer-id')

const peerId1 = PeerId.createFromB58String('QmZjTnYw2TFhn9Nn7tjmPSoTBoY7YRkwPzwSrSbabY24Kp')
const peerId2 = PeerId.createFromB58String('QmZjTnYw2TFhn9Nn7tjmPSoTBoY7YRkwPzwSrSbabY24Kp')

assert.deepEqual(peerId1, peerId2)
// 'bafzbeifjjcie6lypi6ny7amxnfftagclbuxndqonfipmb64f2km2devei4'

peerId1.toString()

assert.deepEqual(peerId1, peerId2)
// Uncaught AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
```

This is because `.toString()` has the side effect of [setting](https://github.com/libp2p/js-peer-id/blob/master/src/index.js#L140) a `._idCIDString` property on `this` which the other peer ID doesn't have.

**Comment by vasco-santos** [comment]
Users should not rely on deepEqual in my opinion, as if you create the same PeerId via privateKey, or B58String they are the same PeerId (per `PeerId.equals`), but the deep will fail.

Even though, we should address this problem. If this is not a major problem, we should probably wait until we move into using default format from [RFC 0001](https://github.com/libp2p/specs/pull/209) by default in libp2p

**Comment by achingbrain** [comment]
> Users should not rely on deepEqual in my opinion

It's a pretty common test assertion.  It could be fixed my marking using `Object.defineProperty` to mark the property as non-enumerable?
