### ISSUE TITLE
fix: CID string incorrectly parsed to PeerId while go-libp2p-core refuses it

### ISSUE THREAD

**Issue by nicobao** [libp2p/js-peer-id#187]
Feeding `bafykbzacecesdmus2x37xyvtxdwlpx3vu5cjecxed473f66fezh6tdoccqhqq` to `PeerId.parse(str)` generate a valid PeerId object, but the same string will generate an error after unmarshalling to CID in `github.com/libp2p/go-libp2p-core/peer`.

**I created the a small repo to reproduce the error, you can try here: https://github.com/nicobao/bug-libp2p-peerid**

Please take a look :).

It outputs:
```
=== JS VERSION ===

> bug-libp2p-peerid@1.0.0 start /home/nicolas/nicobao/bug-libp2p-peerid/js
> node with-js-lib.js

Parsing bafykbzacecesdmus2x37xyvtxdwlpx3vu5cjecxed473f66fezh6tdoccqhqq...
peerId is valid! PeerId {
  _id: Uint8Array(36) [
    160, 228,   2,  32, 137,  33, 178, 146,
    213, 247, 251, 226, 179, 184, 236, 183,
    223, 117, 167,  68, 146,  10, 228,  31,
     63, 178, 251, 197,  38,  79, 233, 141,
    194,  20,  15,   8
  ],
  _idB58String: '2DrjgbDVCNmAACH2oLHRPSg874iiE13cTnHK9dvVhXJqN2UQXR',
  _privKey: undefined,
  _pubKey: undefined
}

=== GO VERSION ===
Parsing bafykbzacecesdmus2x37xyvtxdwlpx3vu5cjecxed473f66fezh6tdoccqhqq ...
Error can't convert CID of type "dag-pb" to a peer ID
```

I tried using https://github.com/libp2p/js-libp2p-peer-id/tree/master/packages/libp2p-peer-id but it doesn't contain enough validation function it seems. 

I want to avoid importing the whole js-libp2p package just for validating peerId.

In this library (js-peer-id) still maintained? What is the idiomatic way to validate peerId in frontend?

Thank you

**Comment by wemeetagain** [comment]
I think this library is no longer maintained and the newest version lives here: https://github.com/libp2p/js-libp2p-peer-id/

**Comment by nicobao** [comment]
This library js-peer-id is still referenced here in `data-types`: https://github.com/libp2p/js-libp2p#packages

**Comment by wemeetagain** [comment]
looks like the readme is out of date

`@libp2p/peer-id` exports ESM only so you have to use ESM import statements or use `await import('@libp2p/peer-id')`

**Comment by nicobao** [comment]
Isn't `import { PeerId } from '@libp2p/peer-id'` already an ESM export statement?

**Comment by nicobao** [comment]
I think this repository should be explicitely deprecated though and redirect to https://github.com/libp2p/js-libp2p-peer-id/

**Comment by mpetrunic** [comment]
https://github.com/libp2p/js-peer-id/pull/179
It will soon be archived
