### ISSUE TITLE
node-forge + webpack (moving to CJS) watch issue

### ISSUE THREAD

**Issue by nginnever** [libp2p/js-peer-id#5]
The Deps folder contains a <a href="https://github.com/digitalbazaar/forge/issues/66">pre-bundled digitalbazaar forge package</a> that is tagged into our building process until forge removes the requirejs boilerplate. There is an <a href="https://github.com/digitalbazaar/forge/pull/357"> open PR</a> that addresses this so this issue is to keep an eye on or assist that PR if possible. 

<a href="https://github.com/ipfs/js-ipfs/blob/master/karma.conf.js">Link</a> to the js-ipfs karma conf, this will show the file path to the forge bundle when peer-id PR is merged.

cc @dignifiedquire

**Comment by diasdavid** [comment]
node-forge no more with https://github.com/libp2p/js-libp2p-crypto :)

Thank you to the folks that made node-forge though, it proved to be super useful :)
