### ISSUE TITLE
Add setters for the keys

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-peer-id#59]
to fix https://github.com/libp2p/js-peer-book/issues/33

make sure that on set of the priv key, the pubkey still matches.

**Comment by dryajov** [comment]
@diasdavid I'll add this, as I need them for circuit. Any considerations that I should take into account?

**Comment by diasdavid** [comment]
@dryajov check here: https://github.com/libp2p/js-peer-id/pull/60 needs better checking. It is annoying because we can't really verify on set (all crypto must be async)
