### ISSUE TITLE
publish latest version to npm

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-peer-id#63]
There are changes in master that havent been published yet, can we get them out to npm?

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/27992467-e2c6d100-648c-11e7-8644-6ddfa4105982.png)

Which features? The last commit was literally a release to npm

**Comment by dryajov** [comment]
My bad, you're right. Peer-info was the only one that had the changes.
