### ISSUE TITLE
Catch error when unmarshaling public key instead of crashing

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-peer-id#71]
This line here https://github.com/libp2p/js-peer-id/blob/master/src/index.js#L173 makes the app crash if the supplied public key isn't valid (for example if the buffer isn't even a protocol buffers object)

Instead the error should be caught and returned via callback

**Comment by mkg20001** [comment]
PR #72

**Comment by diasdavid** [comment]
Continue on #72
