### ISSUE TITLE
.createFromJSON does not check if public key and id match

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-peer-id#79]
.createFromJSON only matches private key => id and private key => public key

Because the private key is optional the public key will not get matched against the id if it is missing.

**Comment by mkg20001** [comment]
Is this fixed now?

**Comment by jacobheun** [comment]
Yes, it looks like it. We verify the private and pub key digests match (if there is a public key) and that the id and priv digest match, which inherently validate the public and id match.
