### ISSUE TITLE
Missing ID validation

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-peer-id#83]
Shouldn't there be some more validation of the ID passed to `PeerId`? 

Currently it's checked to ensure it's a buffer...shouldn't it be checked to ensure it's a valid CID?

Also applies to the commonly used factory functions like [`createFromB58String`](https://github.com/libp2p/js-peer-id/blob/bd1dc9bda02bb709569f6bfce5ddbf93c5736c79/src/index.js#L168), which will ensure the string is base 58 encoded but nothing else.

**Comment by vogdb** [comment]
Hi! Is this still actual? I see that factory functions have validations as of now.

cc @vasco-santos

**Comment by vasco-santos** [comment]
> Hi! Is this still actual? I see that factory functions have validations as of now.

That's correct, thanks
